[IMPROVE] add long date user login verification
CraftMyWebsite/cmw-core pull request #389
Opened 2024-12-11 11:05 UTC by Zomblard

2024-12-11 11:18 UTC, Teyir requested changes

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Controllers/UsersSettingsController.php
> +        [$resetPasswordMethod, $profilePage, $securityReinforced] = Utils::filterInput('reset_password_method', 'profile_page', 'security_reinforced');
Il faudrait arrêter d'utiliser Utils::filterInput() mais plutôt les méthodes du FilterManager
Ça serais top d'utiliser ces bonnes méthodes dès maintenant

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Controllers/UsersSettingsController.php
>          UsersSettingsModel::updateSetting('profilePage', $profilePage);
TODO: BulkdUpdateSettings()

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Entities/UserEntity.php
> +    public function getLastConnectionUnformatted(): string
Problème de nommage...

La méthode doit s'appeler: getLastConnection()

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Models/UsersModel.php
> +    public function addLongDateCode(string $email, string $encryptedCode): void
Return bool (error handling)

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Models/UsersModel.php
> +    public function deleteLongDateCode(string $email): void
Return bool (error handling)

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Models/UsersModel.php
> +        $option = $req->fetch();
Pour plus de sécu il faudrait un check:
```php

if (!$options){
return null;
}
```

2024-12-11 11:18 UTC, Teyir commented on App/Package/Users/Models/UsersModel.php
> +
Pour plus de sécu il faudrait un check:
```php

if (!$options){
return null;
}
```

2024-12-11 11:19 UTC, Teyir commented on App/Package/Users/Controllers/UsersSettingsController.php
>          UsersSettingsModel::updateSetting('profilePage', $profilePage);
Pas forcément à traiter dans cette PR, je l'ajoute sur Notion. US [GEN-65]

2024-12-11 15:34 UTC, Zomblard commented on App/Package/Users/Controllers/UsersSettingsController.php
>          UsersSettingsModel::updateSetting('profilePage', $profilePage);
Hein ??

2024-12-12 15:39 UTC, Zomblard commented on App/Package/Users/Controllers/UsersSettingsController.php
> +        [$resetPasswordMethod, $profilePage, $securityReinforced] = Utils::filterInput('reset_password_method', 'profile_page', 'security_reinforced');
Fera l'objet d'une conversion global

2024-12-13 09:28 UTC, Teyir requested changes
Je m'occupe de ces changements @Zomblard

2024-12-13 09:28 UTC, Teyir commented on App/Package/Core/Views/Theme/themes.admin.view.php
> +                                                class="fa-brands fa-github"></i> GitHub</a>
Je vais être chiant, mais le code n'est pas forcément stocké sur github...

2024-12-13 09:28 UTC, Teyir commented on App/Package/Core/Views/Theme/themes.admin.view.php
> +                            Vous utilisez la version <b><?= $localTheme->version() ?></b>, veuillez mettre à jour vers <b><?= $theme['version_name'] ?></b> !
i18n

2024-12-13 09:28 UTC, Teyir commented on App/Package/Users/Controllers/UsersLoginController.php
> +            ['site_name' => (new CoreModel())->fetchOption('name')]),$body);
Il faut utiliser un singleton.

2024-12-13 09:44 UTC, Teyir approved these changes

2024-12-13 09:45 UTC, merged